# Generated by Django 4.0.2 on 2022-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_client_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
