# Generated by Django 4.0.2 on 2022-02-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_colourvariation_remove_orderitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_colours',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ColourVariation',
        ),
    ]
