# Generated by Django 4.0.2 on 2022-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_orderitem_colour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
